# Numpy

## List & Array (ndarray)
- Array สมาชิกใน Array ต้องมีชนิดข้อมูลเหมือนกัน
- List เป็นสมาชิกมีชนิดข้อมูลต่างกันได้ เช่น ใน list นั้น มีประเภท String ก็ได้หรือ int ก็ได้

- Array ขนาดที่แน่นอนเปลี่ยนแปลงขนาดไม่ได้
- List มีขนาดที่ยืดหยุ่นกว่า

## การสร้าง Array
### 1 มิติ (แถว)

In [86]:
import numpy as np
arr = np.array(1) #สร้างอาร์เลย์ 0 มิติ
arr
arr.ndim #เป็นการบอกมิติของ อาร์เลย์

a = np.array([1,2,3]) #สร้างอาร์เลย์ 1 มิติ
a.ndim #เป็นการบอกมิติของ อาร์เลย์
a.shape #คือ การบอกว่า ใน Array a นั้นมีกี่แถว และมีกี่คอลัมใน Array ใช้บอกโครงสร้างว่าเป็นอย่างไร
a.size #คือ การบอกจำนวนสมาชิกว่ามีกี่ตัว
a.itemsize #คือ การบอก bype
a.dtype #คือ การบอก bit
print(a.dtype) #bit
print(a.itemsize) #bype
print(a.size)
print(a.shape) #มี 3 แถว
##แบบเขียนไว้ในตัวแปรก่อน ค่อยเรียกใช้
lst = [4,3,2,1]
b = np.array(lst)
b

int64
8
3
(3,)


array([4, 3, 2, 1])

### 2 มิติ (แถว, คอลัม)

In [88]:
import numpy as np
a = np.array([[1,2,3],[3,2,1]])
print(f"เป็น {a.shape}") #มี 2 แถว 3 คอลัม 
print(f"มี {a.size} ตัว")
print(f"มี {a.dtype} bit")
print(f"มี {a.itemsize} bype")
print(f"มี {a.ndim} มิติ")

print(f"แถวที่ 0 ตัวที่ 2 คือ {a[0][2]}") #แถวที่ 0 ตัวที่ 2:โดยเริ่มนับจาก0 => 3

lst = ([[1,2,3],[4,5,6],[7,8,9]]) #แถว หลัก
b = np.array(lst)
b

เป็น (2, 3)
มี 6 ตัว
มี int64 bit
มี 8 bype
มี 2 มิติ
แถวที่ 0 ตัวที่ 2 คือ 3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 3 มิติ (แถว, คอลัม, ลึก)

In [89]:
import numpy as np
a = np.array([[[1,2,3],[6,5,4],[11,12,13]]])
print(f"มี {a.ndim} มิติ")
print(f"มี {a.size} ตัว")
print(f"มี {a.dtype} bit")
print(f"มี {a.itemsize} bype")
print(f"เป็น {a.shape}") #ลึก 1 ชั้น 3 แถว 3 คอลัม
print(a)

มี 3 มิติ
มี 9 ตัว
มี int64 bit
มี 8 bype
เป็น (1, 3, 3)
[[[ 1  2  3]
  [ 6  5  4]
  [11 12 13]]]


## การเข้าถึงข้อมูล Array 1,2,3 index

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(f"ในอาร์เลย์นี้ มีค่า คือ {a}")
print(f"ในอาร์เลย์นี้มีมิติ เป็น {a.ndim} มิติ")
print(f"ในแถวที่ 0 ตัวที่ 3 คือ {a[2]}")
print(f"ตัวสุดท้ายและ ตัวที่ 2 บวกกันได้ คือ {a[-1] + a[1]}")
print("="*50)
# =========================================================

b = np.array([[3,2,1],[7,2,6]])
print(f"\nในอาร์เลย์นี้ มีค่า คือ \n{b}")
print(f"ในอาร์เลย์นี้มีมิติ เป็น {b.ndim} มิติ")
print(f"ในแถวที่ 1 ตัวที่ 2 คือ {b[1][1]}")
print(f"ตัวสุดท้ายของแถวที่ 2 และ ตัวที่ 3 ของแถวที่ 1 จะบวกกันได้ เท่ากับ {b[1][2] + b[0][2]}")
print("="*50)
# =========================================================

#ถ้ามี [] ซ้อนกันอยู่แค่ชั้นเดียว แสดงว่า มีแค่ 1 ชั้น จะเรียกใช้โดยเริ่มนับจากชั้นที่ 0
c = np.array([[[5,2,8],[11,28,3],[7,3,1]]])
print(f"\nในอาร์เลย์นี้ มีค่า คือ \n{c}")
print(f"ในอาร์เลย์นี้มีมิติ เป็น {c.ndim} มิติ")
print(f"ในแถวที่ 3 ตัวที่ 1 คือ {c[0][2][0]}")
print(f"ตัวที่ 2 ของแถวที่ 3 บวกกับ ตัวที่ 1 ของแถวที่ 2 และลบกับตัวที่ 3 ของแถวที่ของแถวที่ 1 จะได้ เท่ากับ {c[0][2][1] + c[0][1][0] - c[0][0][2]}") #3+11-8 = 7

ในอาร์เลย์นี้ มีค่า คือ [1 2 3 4 5]
ในอาร์เลย์นี้มีมิติ เป็น 1 มิติ
ในแถวที่ 0 ตัวที่ 3 คือ 3
ตัวสุดท้ายและ ตัวที่ 2 บวกกันได้ คือ 7

ในอาร์เลย์นี้ มีค่า คือ 
[[3 2 1]
 [7 2 6]]
ในอาร์เลย์นี้มีมิติ เป็น 2 มิติ
ในแถวที่ 1 ตัวที่ 2 คือ 2
ตัวสุดท้ายของแถวที่ 2 และ ตัวที่ 3 ของแถวที่ 1 จะบวกกันได้ เท่ากับ 7

ในอาร์เลย์นี้ มีค่า คือ 
[[[ 5  2  8]
  [11 28  3]
  [ 7  3  1]]]
ในอาร์เลย์นี้มีมิติ เป็น 3 มิติ
ในแถวที่ 3 ตัวที่ 1 คือ 7
ตัวที่ 2 ของแถวที่ 3 บวกกับ ตัวที่ 1 ของแถวที่ 2 และลบกับตัวที่ 3 ของแถวที่ของแถวที่ 1 จะได้ เท่ากับ 6


## ชนิดข้อมูล(Data type) หลักๆที่ใช้ใน numpy 

1. Interger
2. Float
3. String
4. Boolean
5. Complex (จำนวนเชิงซ้อน)
6. Object

In [13]:
import numpy as np

#อยากต้องการให้ในอาร์เลย์เป็นจำนวนเต็ม(Integer) จะได้
a = np.array([1,2,3,4,5],dtype="int")
print(a.dtype)
print(a)
print("="*50)

b = np.array([1,2,3,4,5],dtype="float")
print(f"\n{b.dtype}")
print(b)
print("="*50)

c = np.array([1,2,3,4,5],dtype="complex")
print(f"\n{c.dtype}")
print(c)
print("="*50)

int64
[1 2 3 4 5]

float64
[1. 2. 3. 4. 5.]

complex128
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


## Matrix หรือก็คือ Array 2 มิติ 

### Square Matrix (เมทริกซ์จัตุรัส) คือจำนวนแถวและหลักเท่ากัน ==> Array 2D ระบุเองได้เลย แต่ แถวและหลักต้องเท่ากัน

### Zero Matrix (เมทริกซ์ศูนย์) คือ สมาชิกทุกตัวเป็ฯค่า 0

In [48]:
import numpy as np

a = np.zeros(5) #สร้าง เมทริกซ์ศูนย์ จำนวน 5 ตัว 1 มิติ
a1 = np.zeros(5,dtype="int") #บอก Data type
a2 = np.zeros((2,2)) #สร้าง Matrix 2 มิติ จะระบุเป็น Tuple ก็ได้หรือ List ก็ได้
a3 = np.zeros([3,4],dtype="int")

print(f"Array first is {a} Type is Float")
print(f"\nArray second is {a1} Type is Integer")
print(f"\nArray third is \n{a2} 2D Float")
print(f"\nArray fourth is \n{a3} 2D Integer")

Array first is [0. 0. 0. 0. 0.] Type is Float

Array second is [0 0 0 0 0] Type is Integer

Array third is 
[[0. 0.]
 [0. 0.]] 2D Float

Array fourth is 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 2D Integer


## Ones Matrix

In [40]:
import numpy as np 
#จะสร้างแบบเป็ฯไว้ในตัวแปรก็ได้ หรือ เรียกใช้ได้เลยก็ได้
a = np.ones(10)
a = np.ones(10,dtype="int") # 1D
print(f"Array 1D is {a}")

a2D = np.ones([3,3]) #ตอนนี้ยังเป็น float หรือยังมีจุดทศนิยม
a2D = np.ones([3,3],dtype="int") #แปลงเป็นจำนวนเต็ม
print(f"\nArray 2D is \n{a2D}")

Array 1D is [1 1 1 1 1 1 1 1 1 1]

Array 2D is 
[[1 1 1]
 [1 1 1]
 [1 1 1]]


## Matrix ค่าคงที่ (Full)

In [41]:
import numpy as np

a = np.full(5,10) #แบบ 1 มิติ ก็ คือ อยากได้ 5 ตัว และ 5 ตัวนั้นต้องเป็นเลข 10
print(f"Array 1D is {a}")

a2 = np.full([3,3],7) #แบบ 2 มิติ ก็คือ อยากได้แถวและหลัก จำนวน 3X3 และตัวเลขในนั้นเป็นเลข 7
print(f"\nArray 2D is \n{a2}")

Array 1D is [10 10 10 10 10]

Array 2D is 
[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Identity Matrix (เมทริกซ์เอกลักษณ์) คือ เส้นทะเยงมุมทุกตัวต้องเป็น 1 นอกนั้นเป็น 0

In [59]:
import numpy as np

#อิงตาม Matrix จัตุรัส
a = np.identity(4) #Float
a = np.identity(4,dtype="int") #int
print(f"แบบไม่ยืดหยุ่น(ต้องเป็ฯเมทริกซ์จัตุรัสด้วย) คือ \n{a}")

a2 = np.eye(3,5) #3 แถว 5 คอลัม ทแยงเลข 1
print(f"\nแบบยืดหยุ่น(ไม่จำเป็นต้องเป็ฯเมทริกซ์จัตุรัส) คือ \n{a2}")

#คือการย้ายหรือขยับตำแหน่งเลข 1 ไปทางขวา
a3 = np.eye(4, k=1)
print(f"\nขยับเลข 1 ไป 1 ตำแหน่งจะได้ = \n{a3}")

#คือการย้ายหรือขยับตำแหน่งเลข 1 ลง
a4 = np.eye(4, k=-1)
print(f"\nขยับเลข 1 ลงไป 1 ตำแหน่งจะได้ = \n{a4}")

แบบไม่ยืดหยุ่น(ต้องเป็ฯเมทริกซ์จัตุรัสด้วย) คือ 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

แบบยืดหยุ่น(ไม่จำเป็นต้องเป็ฯเมทริกซ์จัตุรัส) คือ 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

ขยับเลข 1 ไป 1 ตำแหน่งจะได้ = 
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

ขยับเลข 1 ลงไป 1 ตำแหน่งจะได้ = 
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## Linspace คือการ Array แบบเว้นระยะเท่าๆกัน 

In [67]:
import numpy as np
#start, stop, number

np.linspace(1,10) # นับ 1-10
np.linspace(1,10,4,dtype="int") #นับ 1-10 เอาแค่ 4 ตัว

np.linspace(1,5, endpoint=False,) #นับเลข 1-5 แต่ไม่เอาเลข5 เอาตัวที่มันใกล้เคียง

array([1.  , 1.08, 1.16, 1.24, 1.32, 1.4 , 1.48, 1.56, 1.64, 1.72, 1.8 ,
       1.88, 1.96, 2.04, 2.12, 2.2 , 2.28, 2.36, 2.44, 2.52, 2.6 , 2.68,
       2.76, 2.84, 2.92, 3.  , 3.08, 3.16, 3.24, 3.32, 3.4 , 3.48, 3.56,
       3.64, 3.72, 3.8 , 3.88, 3.96, 4.04, 4.12, 4.2 , 4.28, 4.36, 4.44,
       4.52, 4.6 , 4.68, 4.76, 4.84, 4.92])

## Arange คือการสร้าง Array แบบกำหนดช่วงข้อมูล 

In [ ]:
import numpy as np
#start, stop, step, dtype คือ เริ่มที่เลขอะไร, จบที่เลขอะไร(ก่อนถึงตัวเลขตัวนั้น), เพิ่มลดค่ากี่ step, บอกชนิดข้อมูล ค่า Default คือ float 

a = np.arange(10) #ตั้งแต่ 0 ก่อน 10 ก็คือเลข 9 จะได้ 0-9
a1 = np.arange(3,10) #อยากได้ 3 ถึง 9
a2 = np.arange(-5,6) #อยากได้ -5 ถึง 5
a3 = np.arange(1,11,2) #นับ 1 ถึง 10 แต่นับขึ้นทีละ2

array([3, 4, 5, 6, 7, 8, 9])

## Random คือ การสร้ง Array โดยการสุ่มค่าตัวเลข

In [73]:
import numpy as np

a = np.random.random((2,2)) # สุ่มค่า ภายใน Array 2 มิติ ตั้งแต่ 0 ก่อน 1
print(f"สุ่มตัวเลขขนาด 2X2 จะได้ \n{a}")

สุ่มตัวเลขขนาด 2X2 จะได้ 
[[0.91852815 0.57049668]
 [0.02339892 0.73725137]]


## Slice Array 1D

In [ ]:
import numpy as np

a = np.arange(1,11)
print(f"แบบยังไม่ระบุจุดเริ่มต้น index {a[:]}") # คือการนำตัวเลขใน Array a มาทั้งหมด
#แบบระบุจุดเริ่มต้น index ที่ 2 ขึ้นไป
print(f"index ที่ 2 ขึ้นไปจะได้ {a[2:]}")
#แบบระบุจุดสิ้นสุด อยากได้เลข 5 
print(f"จะได้ {a[:5]}") #ก็คือการเริ่มนับจากตัวแรกถึงก่อน index ที่ 5

#แบบระบุตัว Step
print(f"เพิ่มทีละ 2 {a[2:9:2]}")#คือ การนับเลข 2 ถึง 9 โดยเพิ่มทีละ 2 หน่วย
print(f"{a[::2]}") #เรื่มจากตัวเริ่มต้น โดยเพิ่มทีละ2

แบบยังไม่ระบุจุดเริ่มต้น index [ 1  2  3  4  5  6  7  8  9 10]
index ที่ 2 ขึ้นไปจะได้ [ 3  4  5  6  7  8  9 10]
จะได้ [1 2 3 4 5]
เพิ่มทีละ 2 [3 5 7 9]
[1 3 5 7 9]


## Slice Array 2D

In [63]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"แบบไม่ระบุ \n{a[:,:]}")
print(f"\nแบบเฉพาะ index ที่ 1 ของแถวและหลักเป็นต้นไป \n{a[1:,1:]}")
print(f"\nแถวที่ 3 หลัก ที่ 2 เป็นต้นไป\n{a[2:,1:]}") #อยากได้ 8,9
print(f"\nคอลัม ที่ 3 \n{a[:,2:]}") #อยากได้แค่ คอลัมที่ 3
print(f"\nแถวที่ 1-2 และเอาคอลัมที่ 3 \n{a[:2,2:]}") #เอาแถวที่ 1-2 และเอาคอลัมที่ 2-3

#เอาแบบที่ แถวหรือหลัก เดี่ยวๆ
print(f"\nแถวที่ 1 คือ {a[:1,:]}") #เอาแค่แถว
print(f"แถวที่ 2 คือ {a[1:2,:]}")
print(f"แถวที่ 3 คือ {a[2:,:]}")
print(f"\nคอลัมที่ 1 คือ \n{a[:,:1]}")
print(f"\nคอลัมที่ 2 คือ \n{a[:,1:2]}")
print(f"\nคอลัมที่ 3 คือ \n{a[:,2:]}")

แบบไม่ระบุ 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

แบบเฉพาะ index ที่ 1 ของแถวและหลักเป็นต้นไป 
[[5 6]
 [8 9]]

แถวที่ 3 หลัก ที่ 2 เป็นต้นไป
[[8 9]]

คอลัม ที่ 3 
[[3]
 [6]
 [9]]

แถวที่ 1-2 และเอาคอลัมที่ 3 
[[3]
 [6]]

แถวที่ 1 คือ [[1 2 3]]
แถวที่ 2 คือ [[4 5 6]]
แถวที่ 3 คือ [[7 8 9]]

คอลัมที่ 1 คือ 
[[1]
 [4]
 [7]]

คอลัมที่ 2 คือ 
[[2]
 [5]
 [8]]

คอลัมที่ 3 คือ 
[[3]
 [6]
 [9]]


## Index Operator

In [ ]:
import numpy as np

x = np.arange(1,11) #แสดงเลข1ถึง10
print(x)
index = np.array([1,5,7])
x[index] #ก็คือ ในตำแน่งที่ 1 5 7 นี้อะ มันเป็นเลขอะไรใน Array ของ x 

[ 1  2  3  4  5  6  7  8  9 10]


array([2, 6, 8])

## ตัวดำเนินการทางคณิตศาสตร์

In [ ]:
import numpy as np

a = np.arange(1,5)
a+2 #ก็คือการบวกเพิ่มไปอีก 2 หน่วย เพิ่มทั้งหมดทั้ง array 
a-2
a*2
a**2
a%2
# ถ้าจะเอา Array อื่นมาบวก ลบ คูณ หาร กันจะต้องมีมีขนาดเท่ากัน

array([ 1,  4,  9, 16])

## Reshape, Resize

In [17]:
import numpy as np

# a จะเปลี่ยนแปลงรูปภาพก็ต่อเมื่อ ใช้คำสั่งตามหลัง แต่ค่า a ยังเท่าเดิม
a = np.arange(10)
a.reshape((2,5)) # เปลี่ยนรูปร่างเป็น 2D จะได้ 2 แถว 5 คอลัม ##ชั่วคราว##
a.resize((2,5)) # เปลี่ยนรูปร่างเป็น 2D จะได้ 2 แถว 5 คอลัม ##ถาวร##
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Flatten

In [36]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
print(f"ก่อนยังไม่เแปลง จะได้ \n{a}")
a.flatten() #เปลี่ยน Array จาก 2D เป็น 1D


c = a.flatten()
#ถ้าอยากเปลี่ยนแปลงข้อมูลก้อนใหม่ และอยากให้ข้อมูลเดิมที่อยู่ใน Array a เปลี่ยนตามไปด้วย
b = a.ravel()
b[0] = 5
print(f"\nแปลงเป็น 1 มิติ \n{c}")
print(f"\nเปลี่ยนตัวเลขที่ 1 เป็นเลข 5 \n{b}")
print(f"\nArray a ปัจจุบัน \n{a}")

ก่อนยังไม่เแปลง จะได้ 
[[1 2]
 [3 4]
 [5 6]]

แปลงเป็น 1 มิติ 
[1 2 3 4 5 6]

เปลี่ยนตัวเลขที่ 1 เป็นเลข 5 
[5 2 3 4 5 6]

Array a ปัจจุบัน 
[[5 2]
 [3 4]
 [5 6]]


## Transpose

In [ ]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
a.transpose() #จากแถวเป็นคอลัม จากคอลัมเป็ฯแถว

array([[1, 3, 5],
       [2, 4, 6]])

## Function Stat

In [49]:
import numpy as np

a = np.array([1,2,3,4,5,6])
print(f"ผลรวม {a.sum()}") #ผลบวกรวม
print(f"ผลคูณ {a.prod()}") #ผลคูณรวม
print(f"ค่าเฉลี่ย {a.mean()}") #ค่าเฉลี่ย
print(f"ค่าสูงสุด {a.max()}")
print(f"ค่าสูงสุด {a.min()}")
print(f"ตำแหน่งที่มากที่สุด คือ {a.argmax()}") #หาตำแหน่งที่มากที่สุด
print(f"ตำแหน่งที่น้อยที่สุด คือ {a.argmin()}")

##Array 2D
#axis 0 คือ แนวตั้ง
#axis 1 คือ แนวนอน

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"\nค่าต่ำสุดใน Aarray b แนวนอน {np.min(b,axis=1)}")#หาค่าต่ำสุดใน array b ในแนวนอน
print(f"ค่าต่ำสุดใน Aarray b แนวนอน {np.min(b,axis=0)}")

ผลรวม 21
ผลคูณ 720
ค่าเฉลี่ย 3.5
ค่าสูงสุด 6
ค่าสูงสุด 1
ตำแหน่งที่มากที่สุด คือ 5
ตำแหน่งที่น้อยที่สุด คือ 0

ค่าต่ำสุดใน Aarray b แนวนอน [1 4 7]
ค่าต่ำสุดใน Aarray b แนวนอน [1 2 3]


## Dot Produnt หรือการคูณสเกลาร์

In [ ]:
import numpy as np


#ต้องมีขนาดเท่ากัน
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]])
print(f"Array a = \n{a}")
print(f"\nArray b = \n{b}")

c = a.dot(b)
print(f"\nเมื่อคูณกันแล้วจะได้ \n{c}")

Array a = 
[[1 2]
 [3 4]]

Array b = 
[[11 12]
 [13 14]]

เมื่อคูณกันแล้วจะได้ 
[[37 40]
 [85 92]]


## Concatenate คือ การรวม Array เป็นก้อนเดียว

In [62]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.concatenate((a,b)) #รวมกันโดยการต่อหลัง
c

array([1, 2, 3, 4, 5, 6, 7, 8])

## Append & Insert

In [77]:
##Append
a = np.array([1,2,3,4])
print(f"แทรกแล้วจะได้ = {np.append(a,100)}") #คือการนำข้อมูลตัวใหม่มาต่อท้าย โดย เลือก Array a แล้วตามด้วยเลขที่อยากจะต่อท้าย

#ระบุแบบ 2 มิติ
b = np.array([[1,4],[7,10]])
print(f"\nจะได้ \n{np.append(b,[[20],[20]],axis=1)}") #ต่อท้ายใน Array d และเพิ่ม [20,20] ในแนวนอน

##Insert
a = np.insert(a,1,67) #Array, ตำแหน่ง, เลขที่ต้องการ
print(f"\nแทรกเลข 67 ลงในตำแหน่งที่ 1 จะได้ {a}")
#แบบ 2D แบบเลขเดียว
b = np.insert(b,1,100,axis=1) #แทรกแนวนอนในตำแหน่งที่ 1
b = np.insert(b,0,67,axis=0)
b
#แบบ 2D แบบหลายเลข
b = np.insert(b,2,[[10],[20]],axis=1)
b

แทรกแล้วจะได้ = [  1   2   3   4 100]

จะได้ 
[[ 1  4 20]
 [ 7 10 20]]

แทรกเลข 67 ลงในตำแหน่งที่ 1 จะได้ [ 1 67  2  3  4]


array([[ 67,  67,  10,  20,  67],
       [  1, 100,  10,  20,   4],
       [  7, 100,  10,  20,  10]])

## การลบสมาชิกใน Array

In [85]:
import numpy as np

a = np.arange(1,11)
np.delete(a, 2) #ก็คือการลบ เลข 3 เพราะเลข 3 คือ index ที่ 2

#แบบ 2D
b = a.reshape((2,5))
np.delete(b,1,axis=1)

array([[ 1,  3,  4,  5],
       [ 6,  8,  9, 10]])

## Split คือการแยกข้อมูลออกเป็นส่วนๆ

In [ ]:
import numpy as np

a = np.arange(1,21)
np.split(a,4) #ก็คือแบ่งเป็น 4 กลุ่ม กลุ่มละเท่าๆกัน ในที่นี้ก็คือกลุ่มละ 5 ตัว

#2D
b = a.reshape(5,4)
np.hsplit(b,4) #แนวตั้ง
np.vsplit(b,5) #แนวนอน

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20]])]